### ISSUE TITLE
Task 9: End-User Documentation and Sample Workflows

### ISSUE THREAD

**Issue by fbouteruche** [fbouteruche/dotnet-prompt#9]
## Overview
Create comprehensive end-user documentation and workflow examples for the dotnet-prompt CLI tool, focusing on the **dotprompt format** and practical usage scenarios. The documentation should be implementation-agnostic and emphasize user workflows, MCP server integration, and real-world examples.

## Dependencies
- **Task 1** (Issue #1): ✅ CLI Foundation - COMPLETED
- **Task 2** (Issue #2): ✅ Dotprompt File Parser - COMPLETED  
- **Task 3** (Issue #3): ✅ Configuration System Core - COMPLETED
- **Task 4.1** (Issue #14): Core Orchestrator Refactoring - requires workflow execution documentation
- **Task 4.2** (Issue #15): SubWorkflowPlugin Implementation - requires sub-workflow documentation
- **Task 7** (Issue #7): File System Tool Foundation - requires built-in tools documentation
- **Task 8** (Issue #8): Integration Testing - requires test examples and validation documentation

## Dependent Tasks
None - this task consolidates documentation for all other components.

## Documentation Philosophy: End-User Focused
The documentation should focus on **what users can accomplish** rather than **how it's implemented internally**. While dotnet-prompt leverages Semantic Kernel internally, this is an implementation detail that should not surface in user-facing documentation.

## Technical Specifications
- **Format**: Markdown files following dotprompt specification examples
- **Hosting**: GitHub repository documentation with clear navigation
- **Examples**: Comprehensive workflow examples using dotprompt format
- **Focus**: Practical usage scenarios and real-world applications

### Documentation Structure (User-Centric)
1. **User Documentation**:
   ```
   docs/
   ├── user-guide/
   │   ├── getting-started.md (installation and first workflow)
   │   ├── installation.md
   │   ├── dotprompt-format.md (comprehensive format specification)
   │   ├── basic-workflows.md (simple examples)
   │   ├── advanced-workflows.md (complex scenarios)
   │   ├── mcp-integration.md (MCP server usage)
   │   └── troubleshooting.md
   ├── reference/
   │   ├── cli-commands.md
   │   ├── configuration-options.md
   │   ├── built-in-tools.md
   │   ├── mcp-servers.md
   │   └── error-codes.md
   └── examples/
       ├── basic-workflows/
       ├── mcp-workflows/
       ├── sub-workflows/
       └── real-world-scenarios/
   ```

2. **Getting Started Guide (Dotprompt-Focused)**:
   ```markdown
   # Getting Started with dotnet-prompt
   
   ## Installation
   ```bash
   dotnet tool install -g dotnet-prompt
   ```
   
   ## Your First Workflow
   Create a file named `hello-world.prompt.md`:
   
   ```yaml
   ---
   name: "hello-world"
   model: "gpt-4o"
   tools: ["file-system"]
   ---
   
   # Hello World Workflow
   
   Create a greeting file at `./output/greeting.txt` with the content:
   "Hello from dotnet-prompt!"
   ```
   
   Run the workflow:
   ```bash
   dotnet-prompt run hello-world.prompt.md
   ```
   ```

3. **Dotprompt Format Documentation**:
   ```markdown
   # Dotprompt Format Specification
   
   ## File Structure
   Dotprompt files use a combination of YAML frontmatter and Markdown content:
   
   ```
   ---
   # YAML frontmatter with configuration
   name: "workflow-name"
   model: "model-identifier"
   tools: ["tool1", "tool2"]
   ---
   
   # Markdown content with natural language instructions
   Your workflow description and instructions here...
   ```
   
   ## Frontmatter Fields
   
   ### Required Fields
   - `name`: Unique identifier for the workflow
   - `model`: AI model to use (e.g., "gpt-4o", "claude-3-sonnet")
   
   ### Optional Fields
   - `tools`: Array of available tools
   - `config`: Model-specific configuration
   - `input`: Input schema definition
   - `dotnet-prompt.mcp`: MCP server configuration
   - `dotnet-prompt.sub-workflows`: Sub-workflow definitions
   ```

4. **MCP Integration Documentation**:
   ```markdown
   # MCP Server Integration
   
   ## Overview
   Model Context Protocol (MCP) servers extend dotnet-prompt with additional capabilities.
   
   ## Configuration
   Add MCP servers to your workflow frontmatter:
   
   ```yaml
   ---
   name: "mcp-example"
   model: "gpt-4o"
   
   dotnet-prompt.mcp:
     - server: "filesystem-mcp"
       version: "1.0.0"
       config:
         allowed_directories: ["./src", "./docs"]
     - server: "github-mcp"
       version: "2.1.0"
       config:
         token: "${GITHUB_TOKEN}"
   ---
   ```
   
   ## Popular MCP Servers
   
   ### Filesystem MCP
   - **Purpose**: Enhanced file system operations
   - **Installation**: `npm install -g @modelcontextprotocol/server-filesystem`
   - **Configuration**: 
     ```yaml
     dotnet-prompt.mcp:
       - server: "filesystem-mcp"
         config:
           allowed_directories: ["./project"]
           max_file_size: "10MB"
     ```
   
   ### GitHub MCP
   - **Purpose**: GitHub repository operations
   - **Installation**: `npm install -g @modelcontextprotocol/server-github`
   - **Configuration**:
     ```yaml
     dotnet-prompt.mcp:
       - server: "github-mcp"
         config:
           token: "${GITHUB_TOKEN}"
           default_repo: "owner/repo"
     ```
   ```

### Example Workflows (Real-World Scenarios)
1. **Code Review Workflow**:
   ```markdown
   # code-review.prompt.md
   ---
   name: "code-review"
   model: "gpt-4o"
   tools: ["file-system"]
   
   dotnet-prompt.mcp:
     - server: "filesystem-mcp"
       config:
         allowed_directories: ["./src"]
   
   input:
     schema:
       files:
         type: array
         description: "List of files to review"
   ---
   
   # Code Review Workflow
   
   Review the specified files for:
   - Code quality and best practices
   - Security vulnerabilities
   - Performance considerations
   - Documentation completeness
   
   Generate a comprehensive review report.
   ```

2. **Documentation Generator**:
   ```markdown
   # docs-generator.prompt.md
   ---
   name: "documentation-generator"
   model: "gpt-4o"
   tools: ["file-system", "project-analysis"]
   
   dotnet-prompt.sub-workflows:
     - name: "api-docs"
       path: "./workflows/api-documentation.prompt.md"
     - name: "user-guide"
       path: "./workflows/user-guide.prompt.md"
   ---
   
   # Documentation Generator
   
   Generate comprehensive documentation for the project including:
   1. API documentation from code analysis
   2. User guides and tutorials
   3. Configuration examples
   ```

## Acceptance Criteria
- [ ] Complete getting started guide for new users
- [ ] Comprehensive dotprompt format specification with examples
- [ ] Detailed MCP server integration guide with popular servers
- [ ] CLI command reference with practical examples
- [ ] Built-in tools documentation with usage scenarios
- [ ] Configuration system guide with hierarchical examples
- [ ] Error handling and troubleshooting guide
- [ ] Example workflows covering major use cases
- [ ] Sub-workflow composition examples
- [ ] All examples are tested and verified to work
- [ ] Documentation is implementation-agnostic (no Semantic Kernel mentions)

## Implementation Notes
1. **Documentation Tools**:
   - Use standard Markdown with clear structure
   - Implement markdown linting for consistency
   - Add documentation validation in CI/CD pipeline
   - Include runnable examples that can be executed

2. **Content Requirements**:
   ```markdown
   Each major section should include:
   - Clear explanations of concepts and capabilities
   - Practical examples that users can run immediately
   - Common pitfalls and how to avoid them
   - References to related documentation sections
   - Troubleshooting for common issues
   ```

3. **Example Workflow Categories**:
   - **Basic**: Simple single-tool workflows
   - **MCP-Enhanced**: Workflows using MCP servers
   - **Composition**: Sub-workflow and complex orchestration
   - **Real-world**: Practical scenarios (code review, documentation, analysis)

4. **MCP Server Documentation**:
   - Installation guides for popular MCP servers
   - Configuration examples for common scenarios
   - Security considerations and best practices
   - Troubleshooting MCP connection issues

## Quality Requirements
1. **Content Quality**:
   - All examples must be tested and verified to work
   - Language should be user-friendly and practical
   - Technical accuracy validated by integration tests
   - Regular review and updates for compatibility

2. **Organization**:
   - Logical progression from basic concepts to advanced usage
   - Consistent terminology and formatting
   - Clear navigation between related sections
   - Search-friendly content organization

3. **Maintenance**:
   - Documentation updates included in feature development
   - Automated validation of code examples
   - Community contribution guidelines
   - Version synchronization with CLI changes

## Definition of Done
- All major features and functionality documented from user perspective
- Getting started guide enables new users to be productive quickly
- Reference documentation covers all CLI commands and options
- MCP integration thoroughly documented with working examples
- Example workflows demonstrate real-world usage patterns
- Troubleshooting guide addresses common user issues
- All code examples are tested and verified to work
- Documentation focuses on user outcomes, not implementation details
- Dotprompt format specification is comprehensive and clear
